version: 0.2
phases:
  install:
    commands: 
    - apt-get update && sudo apt-get install -y gnupg software-properties-common
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg 
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - apt-add-repository "deb [arch=$(dpkg --print-architecture)] htpps://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt install terraform=1.5.7-1

    - curl -L -o /usr/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.0/terragrunt_linux_amd64
    - chmod u+x /usr/bin/terragrunt 
    - export TERRAGRUNT_CONFIG="./terragrunt-$PIPELINE_ENV.hcl"
    - export TERRAGRUNT_LOG_LEVEL="debug"
  build:
    commands: 
    - /usr/bin/terragrunt init -backend-config="region=us-east-1"
    - terraform init --reconfigure
    - /usr/bin/terragrunt validate 
    - /usr/bin/terragrunt plan
    - /usr/bin/terragrunt apply -auto-approve 
    